Repository Arquisoft/wichat_en1c, pull requests merged in 2025-04, with the labels that each got.

#85 feat(stats): 📊 stats service prototype
  .github/workflows/build.yml
  .github/workflows/release.yml
  docker-compose.yml
  sonar-project.properties
  statservice/.dockerignore
  statservice/Dockerfile
  statservice/jest.config.json
  statservice/package-lock.json
  statservice/package.json
  statservice/src/config.js
  statservice/src/index.js
  statservice/src/model.js
  statservice/src/routes/pub/games.js
  statservice/src/routes/pub/index.js
  statservice/src/routes/pub/users.js
  statservice/src/routes/save.js
  statservice/src/utils.js
  statservice/src/validation.js
  statservice/test/data.js
  statservice/test/index.test.js
Labels: 🏗️ type: feat, ⌨️ cat: impl

#92 feat: :sparkles: Webapp second prototype
  .github/workflows/build.yml
  sonar-project.properties
  webapp/Dockerfile
  webapp/e2e/features/game.feature
  webapp/e2e/features/login-form.feature
  webapp/e2e/features/register-form.feature
  webapp/e2e/steps/game.steps.js
  webapp/e2e/steps/login-form.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/e2e/test-environment-setup.js
  webapp/jets.config.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/GameContext.js
  webapp/src/SessionContext.js
  webapp/src/components/BackgroundVideo.js
  webapp/src/components/BackgroundVideo.test.js
  webapp/src/components/Footer.js
  webapp/src/components/Footer.test.js
  webapp/src/components/NavBar.js
  webapp/src/components/PrivateRoute.js
  webapp/src/components/PrivateRoute.test.js
  webapp/src/i18n.js
  webapp/src/index.js
  webapp/src/pages/EndGame.js
  webapp/src/pages/Game.js
  webapp/src/pages/Game.test.js
  webapp/src/pages/Home.js
  webapp/src/pages/Home.test.js
  webapp/src/pages/Login.js
  webapp/src/pages/Login.test.js
  webapp/src/pages/NotFound.js
  webapp/src/pages/NotFound.test.js
  webapp/src/pages/Register.js
  webapp/src/pages/Register.test.js
  webapp/src/pages/Stats.js
  webapp/src/test/App.test.js
  webapp/src/test/BackgroundVideo.test.js
  webapp/src/test/EndGame.test.js
  webapp/src/test/Footer.test.js
  webapp/src/test/Game.test.js
  webapp/src/test/Home.test.js
  webapp/src/test/Login.test.js
  webapp/src/test/NavBar.test.js
  webapp/src/test/NotFound.test.js
  webapp/src/test/PrivateRoute.test.js
  webapp/src/test/Register.test.js
  webapp/src/test/Stats.test.js
Labels: 🏗️ type: feat, ⌨️ cat: impl

#101 feat(gateway): 📝 OpenAPI documentation and minor fixes
  authservice/src/routes/pub/signup.js
  gatewayservice/openapi.yaml
  gatewayservice/src/config.js
  gatewayservice/src/index.js
  gatewayservice/src/proxy.js
  gatewayservice/test/index.test.js
  webapp/src/pages/Stats.js
  webapp/src/test/Stats.test.js
Labels: 📃 type: docs, 🏗️ type: feat, ⌨️ cat: impl

#105 feat: ✨Game Service second prototype
  docker-compose.yml
  gameservice/game-service.js
  gameservice/game-service.test.js
  gameservice/jest.config.json
  gameservice/src/cache.js
  gameservice/src/config.js
  gameservice/src/index.js
  gameservice/src/routes/gameConfig.js
  gameservice/src/routes/hint.js
  gameservice/src/routes/question.js
  gameservice/src/routes/save.js
  gameservice/test/game-service.test.js
  llmservice/llm-service.js
  webapp/src/components/Footer.js
Labels: 🏗️ type: feat, ⌨️ cat: impl

#102 feat(questions): :sparkles: cache update on question service
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/queries.js
  questionservice/question-service.js
  questionservice/question-service.test.js
Labels: ⌨️ cat: impl, ⚡ type: perf

#119 fix(gateway): ❌ fixed OpenAPI not working correctly in production.
  gatewayservice/package.json
  gatewayservice/src/config.js
  gatewayservice/src/index.js
Labels: 🐛 type: bug, 🔒 type: security, ⌨️ cat: impl

#120 fix(gateway): 🐛 fixed username not injecting properly & updated OpenAPI
  gameservice/src/routes/question.js
  gameservice/test/game-service.test.js
  gatewayservice/openapi.yaml
  gatewayservice/src/auth.js
  gatewayservice/src/config.js
  gatewayservice/src/proxy.js
  gatewayservice/test/index.test.js
  gatewayservice/test/mockServer.js
  webapp/src/pages/Game.js
Labels: 🐛 type: bug, ⌨️ cat: impl

#127 fix(stats): :bug: fixed bug with question avg
  statservice/src/routes/pub/users.js
Labels: 🐛 type: bug, ⌨️ cat: impl

#121 feat(webapp): :children_crossing: improved usability of register and login
  docker-compose.yml
  webapp/src/i18n.js
  webapp/src/pages/Login.js
  webapp/src/pages/Register.js
  webapp/src/test/Login.test.js
  webapp/src/test/Register.test.js
Labels: 🏗️ type: feat, ⌨️ cat: impl

#130 fix(stats): :bug: added support for unanswered questions
  authservice/package-lock.json
  common/src/model.js
  gatewayservice/openapi.yaml
  gatewayservice/package-lock.json
  statservice/package-lock.json
  statservice/src/routes/pub/users.js
  statservice/src/validation.js
  statservice/test/data.js
Labels: 🐛 type: bug, ⌨️ cat: impl

#123 feat: :sparkles: Final webapp frontend improvements
  .github/workflows/release.yml
  gameservice/src/cache.js
  gameservice/src/routes/gameConfig.js
  gameservice/src/routes/question.js
  gameservice/src/routes/save.js
  gameservice/test/game-service.test.js
  webapp/e2e/features/game.feature
  webapp/e2e/features/login-form.feature
  webapp/e2e/features/register-form.feature
  webapp/e2e/steps/game.steps.js
  webapp/e2e/steps/login-form.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/e2e/test-environment-setup.js
  webapp/package-lock.json
  webapp/package.json
  webapp/public/custom.svg
  webapp/public/manifest.json
  webapp/public/normal.svg
  webapp/public/pVai.svg
  webapp/src/App.js
  webapp/src/GameContext.js
  webapp/src/components/BackgroundVideo.js
  webapp/src/components/GameCard.js
  webapp/src/components/NavBar.js
  webapp/src/components/PrivateRoute.js
  webapp/src/i18n.js
  webapp/src/pages/CustomGame.js
  webapp/src/pages/EndGame.js
  webapp/src/pages/Game.js
  webapp/src/pages/Home.js
  webapp/src/pages/Login.js
  webapp/src/pages/Stats.js
  webapp/src/test/App.test.js
  webapp/src/test/BackgroundVideo.test.js
  webapp/src/test/CustomGame.test.js
  webapp/src/test/EndGame.test.js
  webapp/src/test/Game.test.js
  webapp/src/test/GameCard.test.js
  webapp/src/test/Home.test.js
  webapp/src/test/NavBar.test.js
  webapp/src/test/PrivateRoute.test.js
  webapp/src/test/Stats.test.js
Labels: ⌨️ cat: impl

#132 Feat/game/prototype
  .github/workflows/release.yml
  docker-compose.yml
  gameservice/Dockerfile
  gameservice/package-lock.json
  gameservice/package.json
  gameservice/src/cache.js
  gameservice/src/config.js
  gameservice/src/index.js
  gameservice/src/routes/gameConfig.js
  gameservice/src/routes/hint.js
  gameservice/src/routes/question.js
  gameservice/src/routes/save.js
  gameservice/test/cache.test.js
  gameservice/test/index.test.js
Labels: 🏗️ type: feat, 🧑‍💻 cat: dev, ⌨️ cat: impl
