Repository Arquisoft/wichat_en1c, pull requests merged in 2025-03, with the labels that each got.

#46 docs: :memo: Fixes to "Introduction and Goals" and "Deployment View"
  docs/images/deployment_view/Level1DeploymentDiagram.png
  docs/src/01_introduction_and_goals.adoc
  docs/src/02_architecture_constraints.adoc
Labels: 📃 type: docs, 🏛️ cat: design

#49 fix 🐛: Include bugfixes from the main course template project
  .github/workflows/release.yml
  README.md
  docker-compose.yml
  llmservice/.dockerignore
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  llmservice/package-lock.json
  llmservice/package.json
  webapp/Dockerfile
  webapp/src/App.js
  webapp/src/components/Login.js
Labels: 🐛 type: bug, 🔒 type: security, ⌨️ cat: impl

#51 docs: 📝Fixes for "Context and Scope" and "Solution Strategy"
  docs/images/03_Business_Context.png
  docs/images/03_Technical_Context.png
  docs/src/04_solution_strategy.adoc
Labels: 📃 type: docs, 🏛️ cat: design

#61 feat(auth): 🔒 implemented authentication service
  .github/workflows/build.yml
  .gitignore
  authservice/.dockerignore
  authservice/Dockerfile
  authservice/package-lock.json
  authservice/package.json
  authservice/src/config.js
  authservice/src/index.js
  authservice/src/model.js
  authservice/src/routes/pub/index.js
  authservice/src/routes/pub/login.js
  authservice/src/routes/pub/signup.js
  authservice/src/routes/verify.js
  authservice/src/validation.js
  authservice/test/index.test.js
  docker-compose.yml
  docs/diagrams/build_block_view.drawio
  docs/images/build_block_view/auth_service.drawio.svg
  docs/src/05_building_block_view.adoc
  sonar-project.properties
  users/authservice/auth-model.js
  users/authservice/auth-service.js
  users/authservice/auth-service.test.js
  users/authservice/package-lock.json
  users/authservice/package.json
  users/userservice/.dockerignore
  users/userservice/Dockerfile
  users/userservice/user-model.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
Labels: 🏗️ type: feat, ⌨️ cat: impl

#67 feat(gateway): 🚄 First prototype of the gateway
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/package-lock.json
  gatewayservice/package.json
  package-lock.json
Labels: 🏗️ type: feat, ⌨️ cat: impl

#70 feat(game):🎮 implemented game service
  .vscode/settings.json
  gameservice/.dockerignore
  gameservice/Dockerfile
  gameservice/game-service.js
  gameservice/game-service.test.js
  gameservice/package-lock.json
  gameservice/package.json
Labels: 🏗️ type: feat, ⌨️ cat: impl

#52 Question service Prototype
  questionservice/.dockerignore
  questionservice/Dockerfile
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/question-service.js
  questionservice/question-service.test.js
Labels: 🏗️ type: feat, ⌨️ cat: impl

#79 fix(ci): 🏷️ fixed release pipeline
  .github/workflows/release.yml
  docker-compose.yml
  webapp/e2e/test-environment-setup.js
Labels: 🐛 type: bug, 🧑‍💻 cat: dev

#82 fix: 🐛 another bug....
  .github/workflows/release.yml
Labels: 🧑‍💻 cat: dev, ⌨️ cat: impl

#89 fix: :lock: fix security issues
  .github/workflows/release.yml
  gameservice/Dockerfile
  gameservice/game-service.test.js
  llmservice/Dockerfile
  questionservice/Dockerfile
Labels: 🐛 type: bug, 🔒 type: security, ⌨️ cat: impl

#84 feat(gateway): :sparkles: revamped gateway service
  docker-compose.yml
  gatewayservice/Dockerfile
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/package-lock.json
  gatewayservice/package.json
  gatewayservice/src/auth.js
  gatewayservice/src/config.js
  gatewayservice/src/index.js
  gatewayservice/src/proxy.js
  gatewayservice/src/swagger.js
  gatewayservice/test/index.test.js
  gatewayservice/test/mockServer.js
  webapp/src/SessionContext.js
  webapp/src/pages/Login.js
  webapp/src/pages/Login.test.js
Labels: 🐛 type: bug, 🏗️ type: feat
